### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by Jadeiscodingg** [Jadeiscodingg/My-CV#1]
My cv website looks good but I think what would make it even better is adding much more descriptive comments to make it easier for me or anyone reviewing my code to understand how I got from one point to another so they can understand well.

**Comment by ArnavVerma170209** [comment]
There are a few changes that can be made which will make the site look better,

1.  elements are not centered properly
2. I would suggest you use your actual photo instead a placeholder ( in webp format)
3. Use proper and uniform margins and padding throughout the site
4. The footer does not need to stick to the bottom
5. Use better coloring schemes
6. Add more projects
